#!/usr/bin/env python3
from pathlib import Path

def replace_once(path,old,new):
    p=Path(path); text=p.read_text(encoding='utf-8'); n=text.count(old)
    if n!=1: raise SystemExit(f'{path}: target count={n}: {old[:100]!r}')
    p.write_text(text.replace(old,new),encoding='utf-8')

# SKILL.md owns only the hot policy. Exact commands/heartbeat mechanics stay in cold docs.
replace_once('SKILL.md',
'''Every owner turn, resume, adapter wake and periodic heartbeat begins with exactly one **parent tick**: `parent_tick.py tick`. The tick reconciles durable truth, collapses deterministic transitions, inspects every live attempt, applies bounded lifecycle supervision, tells the parent whether to continue/launch/yield/update/intervene/finish, and emits the only routine owner-update decision. Wakes are timing hints; they are never proof that supervision is healthy.\n''',
'''Every owner turn, resume or harness wake starts with **`parent_tick.py tick`**. It reconciles, advances decided transitions, monitors live work and returns one continue/launch/yield/update/intervene/finish boundary. Wakes are hints, never supervision truth.\n''')
replace_once('SKILL.md',
'''1. **Tick first.** Select/load exactly one parent harness adapter before the first worker launch. In OpenCode, refresh the project adapter once per parent start/resume and require `tbag_follow` before autonomous wakes. Consume the tick packet instead of manually reconstructing lifecycle state. Launch READY work before housekeeping. If orientation requires technical archaeology, delegate Discovery instead of doing it as parent.\n''',
'''1. **Tick first.** Load one harness adapter, consume the tick packet, and never reconstruct a parallel monitor loop. Launch READY work before housekeeping; delegate technical archaeology to Discovery.\n''')
replace_once('SKILL.md',
'''7. **Continue from durable truth.** Evidence gating is not semantic PASS. Interrupted work that remains inside authority retries retained state. Tick supervision distinguishes active logs, silent anomalous work, and a final report whose process failed to exit. Final-report hangs are retired automatically; confirmed silent stalls are lifecycle-retired so retained state/session recovery can continue instead of burning hours.\n8. **Gate phases; launch/arm/yield attempts.** Completed non-bootstrap phases require a fresh Phase Gate; its readable report lives in run `plan/`. Ordinary `launch` stays detached. Every new OpenCode attempt is immediately `tbag_follow`-armed, but observer wakes are only fast hints; the adapter heartbeat requests periodic ticks when hints are lost. Never run foreground `follow`, sleep/poll, or model-authored wait loops.\n''',
'''7. **Continue from durable truth.** Evidence gating is not semantic PASS. Tick monitoring distinguishes active work, confirmed silence and final-report/no-terminal hangs; lifecycle retirement preserves retained recovery state.\n8. **Gate phases; launch/arm/yield attempts.** Non-bootstrap phases require fresh Phase Gates. In OpenCode, `OPENCODE.md` is the sole protocol: normal detached core `launch`, immediately call `tbag_follow`, then yield. Observer wakes are fast hints; heartbeat ticks recover missed wakes. Never run core `follow` or model-authored wait/poll loops.\n''')
replace_once('SKILL.md',
'''Owner communication is part of the durable parent loop, not an improvisation. `parent_tick.py tick` emits `owner_update.due`, reasons, a token, and bounded purpose-first status. Immediate updates are due for owner decisions, worker intervention/recovery and terminal/project-end state; active work also gets a periodic heartbeat (default 30 minutes) so long jobs do not look abandoned. After actually sending that update, record `parent_tick.py ack-update --token ...`; do not acknowledge an update that was never sent.\n\nOwner reports assume the user does not know task IDs or subsystem jargon. Explain **purpose before internals**, then IDs only as secondary references. State **Status; Decisions/blockers; Material outcomes; Running now; Backlog**. Phase-Gate outcomes are contextual milestones. Never sell task counts as progress. A `completion-candidate` is an explicit project-end boundary: finish the run only after confirming the accepted plan has no remaining obligations; otherwise replan/register the missing work.\n''',
'''The tick decides when an owner update is due: decisions/recovery/end-state immediately, plus a periodic active-work heartbeat. Send its purpose-first digest, then acknowledge its token; never ack an unsent update. State **Status; Decisions/blockers; Material outcomes; Running now; Backlog**. Never sell task counts as progress. `completion-candidate` is an explicit end boundary: finish only after confirming accepted-plan obligations are exhausted; otherwise replan.\n''')

# The documentation tests should pin the RC45 lifecycle boundary, not RC44 wake folklore.
p=Path('tests/test_docs.py'); text=p.read_text(encoding='utf-8')
old='''        self.assertIn("`OPENCODE.md` is the sole protocol",hot)\n        self.assertIn("normal detached core `launch`, immediately call `tbag_follow`",hot)\n        self.assertIn("never run core `follow`",hot)\n        self.assertIn("The only required custom tool is **`tbag_follow`**",oc)\n        self.assertIn("Always make this call",oc); self.assertIn("already_armed:true",oc)\n        self.assertIn("Canonical OpenCode loop",oc)\n        self.assertIn("installer proves the **file on disk**, not the live OpenCode tool registry",oc)\n        self.assertIn("`reconcile-run.live_attempts`",oc)\n        self.assertIn("end the parent turn",oc)\n        self.assertIn("in-memory wake bit",oc)\n        self.assertIn("never polls idleness",oc)\n        self.assertIn("older follow-only project adapters remain compatible",oc)\n'''
new='''        self.assertIn("`OPENCODE.md` is the sole protocol",hot)\n        self.assertIn("normal detached core `launch`, immediately call `tbag_follow`",hot)\n        self.assertIn("Never run core `follow`",hot)\n        self.assertIn("The only required custom tool is **`tbag_follow`**",oc)\n        self.assertIn("parent_tick.py tick",oc); self.assertIn("already_armed:true",oc)\n        self.assertIn("Canonical OpenCode loop",oc)\n        self.assertIn("installer proves the **file on disk**, not the live OpenCode tool registry",oc)\n        self.assertIn("periodic transport heartbeat",oc)\n        self.assertIn("wakes are only fast hints",oc.lower())\n        self.assertIn("in-memory wake bit",oc)\n        self.assertIn("never polls idleness",oc)\n        self.assertIn("older follow-only project adapters remain compatible",oc)\n'''
if text.count(old)!=1: raise SystemExit(f'opencode docs contract count={text.count(old)}')
text=text.replace(old,new)
old='''        self.assertIn("Every live attempt must have the selected harness observer armed",hot)\n        self.assertIn("liveness, not semantic progress",hot)\n        self.assertIn("elapsed/report age",prompts)\n        self.assertIn("progress unknown",prompts)\n        self.assertIn("2h for Grunts and 6h for Analysts",prompts)\n        self.assertIn("dsd_attempt.py inspect",prompts)\n        self.assertIn("detached core launch → immediate `tbag_follow`",prompts)\n'''
new='''        self.assertIn("Tick monitoring distinguishes active work",hot)\n        self.assertIn("heartbeat ticks recover missed wakes",hot)\n        self.assertIn("parent_tick.py tick",prompts)\n        self.assertIn("final-report/no-terminal",prompts)\n        self.assertIn("silent anomalies",prompts)\n        self.assertIn("dsd_attempt.py inspect",prompts)\n        self.assertIn("tbag_follow",prompts)\n'''
if text.count(old)!=1: raise SystemExit(f'long-running docs contract count={text.count(old)}')
p.write_text(text.replace(old,new),encoding='utf-8')
